export const REGISTRATION = 'REGISTRATION';
export const REGISTRATION_PENDING = 'REGISTRATION_PENDING';
export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED';
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED';

export const LOGIN = 'LOGIN';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';

export const LOGOUT = 'LOGOUT';
